name: CI

on:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
  workflow_dispatch:

jobs:
  test:
    name: CI workflow-linter (v2)
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run pytest
        run: pipenv run pytest tests --cov=src

      - name: Check type hinting
        run: pipenv run pytype src
