---
name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  enforce-labels:
    uses: bitwarden/gh-actions/.github/workflows/_enforce-labels.yml@main

  enforce-version-label:
    if: |
      ${{ contains(github.event.*.labels.*.name, 'version:major') == false }} ||
      ${{ contains(github.event.*.labels.*.name, 'version:minor') == false }} ||
      ${{ contains(github.event.*.labels.*.name, 'version:patch') == false }}
    name: Enforce version label
    runs-on: ubuntu-22.04

    steps:
      - name: Check for label
        run: |
          echo "${{ github.event.pull_request.labels }}"
          echo "PR without the version label cannot be merged."
          echo "### :x: PR without the version label cannot be merged" >> $GITHUB_STEP_SUMMARY
          exit 1
