---
name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  enforce-labels:
    name: Enforce labels
    runs-on: ubuntu-22.04
    steps:
      - name: Enforce labels
        uses: bitwarden/gh-actions/.github/workflows/_enforce-labels.yml@main
